monitor.alsa.rules = [
  {
    matches = [
      { node.name = "~alsa_input.*Yeti.*" }
    ]
    actions = {
      update-props = {
        audio.rate = 48000
        audio.format = "S24LE"
        session.suspend-timeout-seconds = 0
        api.alsa.period-size = 256
        api.alsa.headroom = 1024
      }
    }
  }
]
